### ISSUE TITLE
关于播放list问题

### ISSUE THREAD

**Issue by ZenRoi** [gaodeng/Moon-FM-Issue#48]
一直使用castro，便捷性上做得比较人性化些。这并不是说MoonFm就乏善可陈，有一些缺陷如果能得到改进就更好了。

比如：当前列表中已播放完毕的内容能否移除或是后置？当然，如果后置的话新加条目时如选择“待播”，这个条目应该插入到后置内容之前。

**Comment by gaodeng** [comment]
hi，Moon FM开发的初衷，就是因为我自己用的apple podcast 听播客，而 apple podcast 的播放列表，会再播放的过程中，经常变来变去，不可控，才开发了Moon FM.
