### ISSUE TITLE
Bug：打开后立即停止其他 App 播放的内容

### ISSUE THREAD

**Issue by mediter** [gaodeng/Moon-FM-Issue#54]
这一点是和国内各大音乐平台 QQ 音乐、网易云音乐一样的毛病 — 点开后立即停止播放即使 Moon.fm 还没开始播放任何内容

**Comment by gaodeng** [comment]
iOS 还是 android 呢？最新版应该没有这个问题了啊

**Comment by mediter** [comment]
iOS 最新版 1.6.2 已没有这个问题。
