### ISSUE TITLE
error

### ISSUE THREAD

**Issue by park233** [gaodeng/Moon-FM-Issue#61]
```
Error: net::ERR_ABORTED
```

---

Moon FM 0.2.0
Electron 4.2.0
darwin 18.6.0
Locale: zh-CN

**Comment by gaodeng** [comment]
@park233  Moon FM 0.2.0 这个是很老的版本了，请申请到最新版本。

**Comment by park233** [comment]
抱歉，提交问题后我就意识到了好久没更新版本了，还是beta 版，很抱歉给你带来了麻烦

gaodeng <notifications@github.com>于2019年7月10日 周三23:02写道：

**Comment by gaodeng** [comment]
@park233  需要 mac app store 兑换码的话,去telegram群里找我。
