### ISSUE TITLE
没有归档功能

### ISSUE THREAD

**Issue by wudb** [gaodeng/Moon-FM-Issue#65]
首页列表里面我不想听的单集没法去掉，只能放在那里，到时候会越来越多，能不能加上归档的功能，可以去掉这些不想听的单集？

**Comment by gaodeng** [comment]
收听页面是按照时间线排列你订阅的播客最新的节目,类似于以前微博的主页。它只显示最新的,所以不会越来越多。在这个页面，你可以挑选你感兴趣的加入到播放列表来播放，或者点击批量加入播放列表，一次性全部加入。

**Comment by wudb** [comment]
刚刚发现一次性全加入播放列表后，收听列表还在，我就明白你的设计了，我就把播放列表里不听的删掉了，只不过发现删除这步每次都要操作两下
